"use client";

import { useState } from "react";
import toast from "react-hot-toast";
import type { Note } from "@/db/schema";

interface NoteCardProps {
  note: Note;
}

function formatDate(d: Date | string | null): string {
  if (!d) return "";
  const date = typeof d === "string" ? new Date(d) : d;
  return new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(date);
}

function buildStandardClipboard(note: Note): string {
  const parts: string[] = [];
  if (note.chiefComplaint)
    parts.push(`CHIEF COMPLAINT: ${note.chiefComplaint}`);
  if (note.hpi) parts.push(`HPI: ${note.hpi}`);
  if (note.objective) parts.push(`OBJECTIVE: ${note.objective}`);
  if (note.assessment) parts.push(`ASSESSMENT: ${note.assessment}`);
  if (note.plan) parts.push(`PLAN: ${note.plan}`);
  parts.push("");
  parts.push("Generated by AI Smart Scribe · aismartscribe.com");
  return parts.join("\n\n");
}

function buildOptomateClipboard(note: Note): string {
  const subjective = [note.chiefComplaint, note.hpi].filter(Boolean).join("\n");
  const parts: string[] = [];
  if (subjective) parts.push(`S: ${subjective}`);
  if (note.objective) parts.push(`O: ${note.objective}`);
  if (note.assessment) parts.push(`A: ${note.assessment}`);
  if (note.plan) parts.push(`P: ${note.plan}`);
  return parts.join("\n\n");
}

async function copyToClipboard(text: string, successMsg: string) {
  try {
    await navigator.clipboard.writeText(text);
    toast.success(successMsg);
  } catch {
    toast.error("Couldn't copy to clipboard");
  }
}

export function NoteCard({ note }: NoteCardProps) {
  const [expanded, setExpanded] = useState(false);
  const createdAtLabel = formatDate(note.approvedAt ?? note.createdAt);
  const preview = note.chiefComplaint?.trim() || "Clinical encounter";

  return (
    <article
      className={`note-card${expanded ? " expanded" : ""}`}
      data-note-id={note.id}
    >
      <button
        type="button"
        className="note-card-header"
        onClick={() => setExpanded((v) => !v)}
        aria-expanded={expanded}
      >
        <div className="note-card-header-main">
          <div className="note-card-meta">
            <span className="note-card-type">Annual Eye Exam</span>
            <span className="note-card-dot" aria-hidden>
              ·
            </span>
            <time className="note-card-date">{createdAtLabel}</time>
          </div>
          <h3 className="note-card-preview">{preview}</h3>
        </div>
        <span className="note-card-chev" aria-hidden>
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            width="18"
            height="18"
          >
            <polyline points="6 9 12 15 18 9" />
          </svg>
        </span>
      </button>

      {expanded && (
        <div className="note-card-body">
          <div className="note-soap">
            <Section label="Chief Complaint" value={note.chiefComplaint} tone="s" />
            <Section label="HPI" value={note.hpi} tone="s" />
            <Section label="Objective" value={note.objective} tone="o" />
            <Section label="Assessment" value={note.assessment} tone="a" />
            <Section label="Plan" value={note.plan} tone="p" />
          </div>

          <div className="note-card-actions">
            <button
              type="button"
              className="btn btn-ghost btn-sm"
              onClick={() =>
                copyToClipboard(
                  buildStandardClipboard(note),
                  "Note copied to clipboard",
                )
              }
            >
              Copy to Clipboard
            </button>
            <button
              type="button"
              className="btn btn-primary btn-sm"
              onClick={() =>
                copyToClipboard(
                  buildOptomateClipboard(note),
                  "Formatted for Optomate — paste into chart",
                )
              }
            >
              Copy for Optomate
            </button>
          </div>
        </div>
      )}
    </article>
  );
}

function Section({
  label,
  value,
  tone,
}: {
  label: string;
  value: string | null;
  tone: "s" | "o" | "a" | "p";
}) {
  if (!value) return null;
  return (
    <div className="note-soap-section">
      <div className={`note-soap-label tone-${tone}`}>{label}</div>
      <div className="note-soap-text">{value}</div>
    </div>
  );
}
